# Generated by Django 3.1.7 on 2021-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_auto_20210322_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='label',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic'), ('FA', 'Farsi'), ('TG', 'Tajik'), ('KY', 'Kyrgyz'), ('UZ', 'Uzbek')], max_length=10),
        ),
    ]
