# Generated by Django 3.1.7 on 2021-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_auto_20210325_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='_memory',
            field=models.TextField(default='{}'),
        ),
    ]
