# Generated by Django 3.1.7 on 2021-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_botuser__memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
