# Generated by Django 3.1.7 on 2021-03-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('RU', 'Русский'), ('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic'), ('FA', 'Farsi'), ('TG', 'Tajik'), ('KY', 'Kyrgyz'), ('UZ', 'Uzbek')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('default_text', models.TextField()),
                ('is_hint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_text', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Stage title')),
                ('is_final', models.BooleanField(default=False, verbose_name='Is final stage')),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='quiz.qbutton', verbose_name='Stage link button')),
                ('children', models.ManyToManyField(related_name='related_to', to='quiz.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.message')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', through='quiz.StageMessage', to='quiz.Message'),
        ),
        migrations.AddField(
            model_name='stage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='quiz.message', verbose_name='Stage question'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_from', models.CharField(choices=[('site', 'Site'), ('telegram', 'Telegram')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('_steps', models.TextField(blank=True, default='[]')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language')),
            ],
        ),
        migrations.CreateModel(
            name='QButtonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qbutton')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.message')),
            ],
        ),
    ]
